#!/usr/bin/perl

# Copyright (C) 2006 Brailcom, o.p.s.
#
# Author: Milan Zamazal <pdm@brailcom.org>
#
# COPYRIGHT NOTICE
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.

use MIDI;
use Getopt::Long;

sub usage ()
{
    print "usage: lilymidi [ --filter-tracks PATTERN [ --prefix-tracks PREFIX ] | --dump ] FILE\n";
    exit 1;
}

$result = GetOptions ("help" => \$opt_help,
                      "filter-tracks=s" => \$opt_filter_tracks,
                      "prefix-tracks=s" => \$opt_prefix_tracks,
                      "dump" => \$opt_dump);
if ($opt_help || @ARGV != 1)
{
    usage ();
}
$file = $ARGV[0];

$opus = MIDI::Opus->new ({'from_file' => $file});
$i = 1;
@track_names = map {
    my @events = $_->events ();
    my $name = "";
    my $found = 0;
    foreach my $e (@events)
    {
        if ($$e[0] eq "track_name")
        {
            $name = $$e[2];
            $found++;
        }
        elsif ($$e[0] eq "patch_change")
        {
            $i = $$e[2] + 1;
            $found++;
        }
        if ($found >= 2) { last; }
    }
    my @item = ($i++, $name);
    \@item;
} $opus->tracks ();;

if ($opt_dump)
{
    $opus->dump ({'dump_tracks' => '1'});
}
elsif ($opt_filter_tracks)
{
    my @numbers = ();
    foreach my $name (@track_names)
    {
        if ($$name[1] =~ $opt_filter_tracks)
        {
            push @numbers, ($$name[0]);
        }
    }
    if ($opt_prefix_tracks && @numbers)
    {
        print $opt_prefix_tracks . " ";
    }
    print join ',', @numbers;
}
else
{
    foreach my $name (@track_names)
    {
        print $$name[0] . " " . $$name[1] . "\n";
        ++$i;
    }
}

__END__
